import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { scoreProduct } from "../product-intelligence.mjs";
import { analyzePerformance } from "../performance-brain.mjs";
import { normalizeProductPerformance } from "../tiktok-shop-client.mjs";

const server = await fs.readFile(new URL("../server.mjs", import.meta.url), "utf8");
const pkg = JSON.parse(await fs.readFile(new URL("../package.json", import.meta.url), "utf8"));
const scheduler = await fs.readFile(new URL("../autonomy-scheduler.mjs", import.meta.url), "utf8");
const shopClient = await fs.readFile(new URL("../tiktok-shop-client.mjs", import.meta.url), "utf8");

assert.match(server, /v2\/auth\/authorize\//);
assert.match(server, /v2\/oauth\/token\//);
assert.match(server, /grant_type: "authorization_code"/);
assert.match(server, /grant_type: "refresh_token"/);
assert.match(server, /\/api\/tiktok\/creator-info/);
assert.match(server, /\/api\/tiktok\/publish-url/);
assert.match(server, /\/api\/tiktok\/publish-status/);
assert.match(server, /\/api\/tiktok\/performance/);
assert.match(server, /\/api\/shop\/products/);
assert.match(server, /\/api\/shop\/orders/);
assert.match(server, /\/api\/shop\/product-performance/);
assert.match(shopClient, /analytics\/202605\/shop_products\/performance/);
assert.match(server, /product_status_filter/);
assert.match(server, /performance = tiktokShopClient\.normalizeProductPerformance/);
assert.match(server, /\/api\/robot\/cycle/);
assert.match(server, /\/api\/autonomy\/emergency-stop/);
assert.match(server, /\/api\/ai\/generate/);
assert.match(server, /tiktokShopClient/);
assert.match(server, /runAutonomousCycle/);
assert.match(server, /startAutonomyScheduler/);
assert.match(server, /ROBOT_AUTONOMY_ENABLED/);
assert.match(scheduler, /startAutonomyScheduler/);
assert.match(scheduler, /source: "autonomous_scheduler"/);
assert.match(server, /\/api\/tiktok\/upload-init/);
assert.match(server, /\/api\/content\/prepare/);
assert.match(server, /\/api\/sales\/plan/);
assert.match(server, /\/api\/sales\/analyze/);
assert.match(server, /\/api\/product-intelligence/);
assert.match(server, /\/api\/content\/factory/);
assert.match(server, /\/api\/autonomy\/policy/);
assert.match(server, /\/api\/experiments/);
assert.match(server, /\/api\/tasks\/engine/);
assert.match(server, /buildProductIntelligence/);
assert.match(server, /shopCredentialsConfigured/);
assert.match(server, /autonomous_loop_requested/);
assert.match(server, /buildContentFactory/);
assert.match(server, /autonomyPolicy/);
assert.match(server, /buildSalesPlan/);
assert.match(server, /analyzePerformance/);
assert.match(server, /\/api\/tasks/);
assert.match(server, /\/api\/tiktok\/upload-chunk\/:upload_id/);
assert.match(server, /Content-Range/);
assert.match(server, /Content-Length/);
assert.match(server, /totalChunkCount/);
assert.match(server, /nextByte/);
assert.match(server, /chunkIndex/);
assert.match(server, /tiktok_completed_before_expected_final_chunk/);
assert.match(server, /tiktok_did_not_complete_final_chunk/);
assert.match(server, /task\.openId = session\.openId \|\| null/);

assert.match(server, /app\.get\(\/\^/);
assert.match(server, /tiktok\(\[A-Za-z0-9\]\{24,80\}\)/);
assert.match(server, /\\\.txt\$\//);
assert.match(server, /PULL_FROM_URL/);
assert.match(server, /timingSafeEqual/);
assert.match(server, /HttpOnly/);
assert.match(server, /X-Content-Type-Options/);
assert.match(server, /rateLimit/);
assert.match(server, /brand_organic_toggle/);
assert.match(server, /is_aigc/);
assert.match(server, /next_cursor/);
assert.match(server, /SameSite=Lax/);
assert.match(server, /escapeHtml/);
assert.match(server, /MEMORY_CLEANUP_INTERVAL_MS/);
assert.match(server, /TASK_RETENTION_MS/);
assert.match(server, /UPLOAD_JOB_RETENTION_MS/);
assert.match(server, /cleanupMemoryState/);
assert.doesNotMatch(server, /TIKTOK_CLIENT_SECRET\s*=\s*["'][^"']+["']/);
assert.equal(pkg.scripts.start, "node server.mjs");

const missingSignals = scoreProduct({ id: "p1", name: "No Data" });
assert.equal(missingSignals.opportunity_score, null);
const stockOnly = scoreProduct({ id: "p2", stock_score: 80 });
assert.equal(stockOnly.opportunity_score, 80);
const perf = analyzePerformance({ items: [{ id: "v1", views: 1000, likes: 100, comments: 20, shares: 10, conversions: 10 }] });
assert.equal(perf.items[0].conversion_rate, 1);
assert.ok(perf.items[0].score > 0 && perf.items[0].score < 100);
const analytics = normalizeProductPerformance({ data: { products: [{ id: "p1", title: "Demo", total_performance: { product_impressions: 1000, product_clicks: 100, click_order_rate: "0.08", estimated_customers: 5, gmv_incl_tax: { amount: "123.45" } } }] } });
assert.equal(analytics[0].signals.impressions, 1000);
assert.equal(analytics[0].signals.clicks, 100);
assert.equal(analytics[0].signals.gmv, 123.45);

console.log("Robot AI smoke checks passed.");
