import assert from "node:assert/strict";
import fs from "node:fs/promises";

const server = await fs.readFile(new URL("../server.mjs", import.meta.url), "utf8");
const pkg = JSON.parse(await fs.readFile(new URL("../package.json", import.meta.url), "utf8"));

assert.match(server, /v2\/auth\/authorize\//);
assert.match(server, /v2\/oauth\/token\//);
assert.match(server, /grant_type: "authorization_code"/);
assert.match(server, /grant_type: "refresh_token"/);
assert.match(server, /\/api\/tiktok\/creator-info/);
assert.match(server, /\/api\/tiktok\/publish-url/);
assert.match(server, /\/api\/tiktok\/publish-status/);
assert.match(server, /\/api\/tiktok\/performance/);
assert.match(server, /\/api\/tiktok\/upload-init/);
assert.match(server, /\/api\/content\/prepare/);
assert.match(server, /\/api\/sales\/plan/);
assert.match(server, /\/api\/sales\/analyze/);
assert.match(server, /\/api\/product-intelligence/);
assert.match(server, /\/api\/content\/factory/);
assert.match(server, /\/api\/autonomy\/policy/);
assert.match(server, /\/api\/experiments/);
assert.match(server, /\/api\/tasks\/engine/);
assert.match(server, /buildProductIntelligence/);
assert.match(server, /buildContentFactory/);
assert.match(server, /autonomyPolicy/);
assert.match(server, /buildSalesPlan/);
assert.match(server, /analyzePerformance/);
assert.match(server, /\/api\/tasks/);
assert.match(server, /\/api\/tiktok\/upload-chunk\/:upload_id/);
assert.match(server, /Content-Range/);
assert.match(server, /Content-Length/);
assert.match(server, /totalChunkCount/);
assert.match(server, /nextByte/);
assert.match(server, /chunkIndex/);
assert.match(server, /tiktok_completed_before_expected_final_chunk/);
assert.match(server, /tiktok_did_not_complete_final_chunk/);
assert.match(server, /task\.openId = session\.openId \|\| null/);

assert.match(server, /app\.get\(\/\^/);
assert.match(server, /tiktok\(\[A-Za-z0-9\]\{24,80\}\)/);
assert.match(server, /\\\.txt\$\//);
assert.match(server, /PULL_FROM_URL/);
assert.match(server, /timingSafeEqual/);
assert.match(server, /HttpOnly/);
assert.match(server, /SameSite=Lax/);
assert.match(server, /escapeHtml/);
assert.match(server, /MEMORY_CLEANUP_INTERVAL_MS/);
assert.match(server, /TASK_RETENTION_MS/);
assert.match(server, /UPLOAD_JOB_RETENTION_MS/);
assert.match(server, /cleanupMemoryState/);
assert.doesNotMatch(server, /TIKTOK_CLIENT_SECRET\s*=\s*["'][^"']+["']/);
assert.equal(pkg.scripts.start, "node server.mjs");

console.log("Robot AI smoke checks passed.");
